site_name: PulseTCG Docs

nav:
  - Home: index.md
  - Portfolio:
    - Portfolio: portfolio.md
    - Watchlist: watchlist.md
    - Binders: binders.md
    - Market Analysis: marketAnalysis.md
    - Buy & Sell: buySell.md
    - Submissions: submissions.md
  - Vending:
    - Vending: vending.md
    - Vending Dashboard: vendingDash.md
    - Vending Inventory: vendingInv.md
    - Vending Transactions: vendingTrans.md
    - Vending Sales: vendingSales.md
    - Vending Purchases: vendingPurchases.md
    - Vending Trades : vendingTrades.md
    - Vending Health: vendingHealth.md

theme: readthedocs